/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransferRequestRouteImport } from './routes/transfer-request'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as StockAdjustmentRouteImport } from './routes/stock-adjustment'
import { Route as RequestForQuotationRouteImport } from './routes/request-for-quotation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiveItemRouteImport } from './routes/receive-item'
import { Route as QuotationEntryRouteImport } from './routes/quotation-entry'
import { Route as PurchaseReturnRouteImport } from './routes/purchase-return'
import { Route as PurchaseRequisitionRouteImport } from './routes/purchase-requisition'
import { Route as PurchaseReportsRouteImport } from './routes/purchase-reports'
import { Route as ProductionReportsRouteImport } from './routes/production-reports'
import { Route as ProductionEntryNewRouteImport } from './routes/production-entry-new'
import { Route as ProductionEntryRouteImport } from './routes/production-entry'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as OrderManagementRouteImport } from './routes/order-management'
import { Route as MrpRouteImport } from './routes/mrp'
import { Route as MealPlanningRouteImport } from './routes/meal-planning'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ItemIssueRouteImport } from './routes/item-issue'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HygieneMonitoringRouteImport } from './routes/hygiene-monitoring'
import { Route as EquipmentReturnsRouteImport } from './routes/equipment-returns'
import { Route as EquipmentMaintenanceRouteImport } from './routes/equipment-maintenance'
import { Route as EquipmentDamageRouteImport } from './routes/equipment-damage'
import { Route as DispatchMonitoringRouteImport } from './routes/dispatch-monitoring'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DemandOrdersRouteImport } from './routes/demand-orders'
import { Route as CookingTempRouteImport } from './routes/cooking-temp'
import { Route as ConsumableUsageRouteImport } from './routes/consumable-usage'
import { Route as ConsumableAllocationRouteImport } from './routes/consumable-allocation'
import { Route as ConfigWarehouseRouteImport } from './routes/config-warehouse'
import { Route as ConfigSupplierRouteImport } from './routes/config-supplier'
import { Route as ConfigPriceRouteImport } from './routes/config-price'
import { Route as ConfigOfficeRouteImport } from './routes/config-office'
import { Route as ConfigItemRouteImport } from './routes/config-item'
import { Route as ConfigCompanyRouteImport } from './routes/config-company'
import { Route as ConfigApprovalRouteImport } from './routes/config-approval'
import { Route as ConfigAirlineRouteImport } from './routes/config-airline'
import { Route as ComparativeStatementRouteImport } from './routes/comparative-statement'
import { Route as BomRouteImport } from './routes/bom'
import { Route as BakeryRouteImport } from './routes/bakery'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApprovalManagementRouteImport } from './routes/approval-management'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AirlineEquipmentsRouteImport } from './routes/airline-equipments'
import { Route as AirlineConsumablesRouteImport } from './routes/airline-consumables'
import { Route as AccountsInvoicesRouteImport } from './routes/accounts-invoices'
import { Route as AccountsExpensesRouteImport } from './routes/accounts-expenses'
import { Route as AccountsApprovalsRouteImport } from './routes/accounts-approvals'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRequestRoute = TransferRequestRouteImport.update({
  id: '/transfer-request',
  path: '/transfer-request',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentRoute = StockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestForQuotationRoute = RequestForQuotationRouteImport.update({
  id: '/request-for-quotation',
  path: '/request-for-quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveItemRoute = ReceiveItemRouteImport.update({
  id: '/receive-item',
  path: '/receive-item',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationEntryRoute = QuotationEntryRouteImport.update({
  id: '/quotation-entry',
  path: '/quotation-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnRoute = PurchaseReturnRouteImport.update({
  id: '/purchase-return',
  path: '/purchase-return',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequisitionRoute = PurchaseRequisitionRouteImport.update({
  id: '/purchase-requisition',
  path: '/purchase-requisition',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReportsRoute = PurchaseReportsRouteImport.update({
  id: '/purchase-reports',
  path: '/purchase-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionReportsRoute = ProductionReportsRouteImport.update({
  id: '/production-reports',
  path: '/production-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionEntryNewRoute = ProductionEntryNewRouteImport.update({
  id: '/production-entry-new',
  path: '/production-entry-new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionEntryRoute = ProductionEntryRouteImport.update({
  id: '/production-entry',
  path: '/production-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderManagementRoute = OrderManagementRouteImport.update({
  id: '/order-management',
  path: '/order-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MrpRoute = MrpRouteImport.update({
  id: '/mrp',
  path: '/mrp',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanningRoute = MealPlanningRouteImport.update({
  id: '/meal-planning',
  path: '/meal-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIssueRoute = ItemIssueRouteImport.update({
  id: '/item-issue',
  path: '/item-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HygieneMonitoringRoute = HygieneMonitoringRouteImport.update({
  id: '/hygiene-monitoring',
  path: '/hygiene-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentReturnsRoute = EquipmentReturnsRouteImport.update({
  id: '/equipment-returns',
  path: '/equipment-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentMaintenanceRoute = EquipmentMaintenanceRouteImport.update({
  id: '/equipment-maintenance',
  path: '/equipment-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentDamageRoute = EquipmentDamageRouteImport.update({
  id: '/equipment-damage',
  path: '/equipment-damage',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchMonitoringRoute = DispatchMonitoringRouteImport.update({
  id: '/dispatch-monitoring',
  path: '/dispatch-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandOrdersRoute = DemandOrdersRouteImport.update({
  id: '/demand-orders',
  path: '/demand-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingTempRoute = CookingTempRouteImport.update({
  id: '/cooking-temp',
  path: '/cooking-temp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableUsageRoute = ConsumableUsageRouteImport.update({
  id: '/consumable-usage',
  path: '/consumable-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableAllocationRoute = ConsumableAllocationRouteImport.update({
  id: '/consumable-allocation',
  path: '/consumable-allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigWarehouseRoute = ConfigWarehouseRouteImport.update({
  id: '/config-warehouse',
  path: '/config-warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigSupplierRoute = ConfigSupplierRouteImport.update({
  id: '/config-supplier',
  path: '/config-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPriceRoute = ConfigPriceRouteImport.update({
  id: '/config-price',
  path: '/config-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigOfficeRoute = ConfigOfficeRouteImport.update({
  id: '/config-office',
  path: '/config-office',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigItemRoute = ConfigItemRouteImport.update({
  id: '/config-item',
  path: '/config-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigCompanyRoute = ConfigCompanyRouteImport.update({
  id: '/config-company',
  path: '/config-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigApprovalRoute = ConfigApprovalRouteImport.update({
  id: '/config-approval',
  path: '/config-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigAirlineRoute = ConfigAirlineRouteImport.update({
  id: '/config-airline',
  path: '/config-airline',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeStatementRoute = ComparativeStatementRouteImport.update({
  id: '/comparative-statement',
  path: '/comparative-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryRoute = BakeryRouteImport.update({
  id: '/bakery',
  path: '/bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalManagementRoute = ApprovalManagementRouteImport.update({
  id: '/approval-management',
  path: '/approval-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlineEquipmentsRoute = AirlineEquipmentsRouteImport.update({
  id: '/airline-equipments',
  path: '/airline-equipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AirlineConsumablesRoute = AirlineConsumablesRouteImport.update({
  id: '/airline-consumables',
  path: '/airline-consumables',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsInvoicesRoute = AccountsInvoicesRouteImport.update({
  id: '/accounts-invoices',
  path: '/accounts-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsExpensesRoute = AccountsExpensesRouteImport.update({
  id: '/accounts-expenses',
  path: '/accounts-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsApprovalsRoute = AccountsApprovalsRouteImport.update({
  id: '/accounts-approvals',
  path: '/accounts-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/airline-consumables': typeof AirlineConsumablesRoute
  '/airline-equipments': typeof AirlineEquipmentsRoute
  '/amenities': typeof AmenitiesRoute
  '/approval-management': typeof ApprovalManagementRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/comparative-statement': typeof ComparativeStatementRoute
  '/config-airline': typeof ConfigAirlineRoute
  '/config-approval': typeof ConfigApprovalRoute
  '/config-company': typeof ConfigCompanyRoute
  '/config-item': typeof ConfigItemRoute
  '/config-office': typeof ConfigOfficeRoute
  '/config-price': typeof ConfigPriceRoute
  '/config-supplier': typeof ConfigSupplierRoute
  '/config-warehouse': typeof ConfigWarehouseRoute
  '/consumable-allocation': typeof ConsumableAllocationRoute
  '/consumable-usage': typeof ConsumableUsageRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/equipment-damage': typeof EquipmentDamageRoute
  '/equipment-maintenance': typeof EquipmentMaintenanceRoute
  '/equipment-returns': typeof EquipmentReturnsRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/mrp': typeof MrpRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-entry-new': typeof ProductionEntryNewRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-reports': typeof PurchaseReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/quotation-entry': typeof QuotationEntryRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/request-for-quotation': typeof RequestForQuotationRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/transfer': typeof TransferRoute
  '/transfer-request': typeof TransferRequestRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/airline-consumables': typeof AirlineConsumablesRoute
  '/airline-equipments': typeof AirlineEquipmentsRoute
  '/amenities': typeof AmenitiesRoute
  '/approval-management': typeof ApprovalManagementRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/comparative-statement': typeof ComparativeStatementRoute
  '/config-airline': typeof ConfigAirlineRoute
  '/config-approval': typeof ConfigApprovalRoute
  '/config-company': typeof ConfigCompanyRoute
  '/config-item': typeof ConfigItemRoute
  '/config-office': typeof ConfigOfficeRoute
  '/config-price': typeof ConfigPriceRoute
  '/config-supplier': typeof ConfigSupplierRoute
  '/config-warehouse': typeof ConfigWarehouseRoute
  '/consumable-allocation': typeof ConsumableAllocationRoute
  '/consumable-usage': typeof ConsumableUsageRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/equipment-damage': typeof EquipmentDamageRoute
  '/equipment-maintenance': typeof EquipmentMaintenanceRoute
  '/equipment-returns': typeof EquipmentReturnsRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/mrp': typeof MrpRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-entry-new': typeof ProductionEntryNewRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-reports': typeof PurchaseReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/quotation-entry': typeof QuotationEntryRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/request-for-quotation': typeof RequestForQuotationRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/transfer': typeof TransferRoute
  '/transfer-request': typeof TransferRequestRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/airline-consumables': typeof AirlineConsumablesRoute
  '/airline-equipments': typeof AirlineEquipmentsRoute
  '/amenities': typeof AmenitiesRoute
  '/approval-management': typeof ApprovalManagementRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/comparative-statement': typeof ComparativeStatementRoute
  '/config-airline': typeof ConfigAirlineRoute
  '/config-approval': typeof ConfigApprovalRoute
  '/config-company': typeof ConfigCompanyRoute
  '/config-item': typeof ConfigItemRoute
  '/config-office': typeof ConfigOfficeRoute
  '/config-price': typeof ConfigPriceRoute
  '/config-supplier': typeof ConfigSupplierRoute
  '/config-warehouse': typeof ConfigWarehouseRoute
  '/consumable-allocation': typeof ConsumableAllocationRoute
  '/consumable-usage': typeof ConsumableUsageRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/equipment-damage': typeof EquipmentDamageRoute
  '/equipment-maintenance': typeof EquipmentMaintenanceRoute
  '/equipment-returns': typeof EquipmentReturnsRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/mrp': typeof MrpRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-entry-new': typeof ProductionEntryNewRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-reports': typeof PurchaseReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/purchase-return': typeof PurchaseReturnRoute
  '/quotation-entry': typeof QuotationEntryRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/request-for-quotation': typeof RequestForQuotationRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/transfer': typeof TransferRoute
  '/transfer-request': typeof TransferRequestRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/airline-consumables'
    | '/airline-equipments'
    | '/amenities'
    | '/approval-management'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/comparative-statement'
    | '/config-airline'
    | '/config-approval'
    | '/config-company'
    | '/config-item'
    | '/config-office'
    | '/config-price'
    | '/config-supplier'
    | '/config-warehouse'
    | '/consumable-allocation'
    | '/consumable-usage'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/equipment-damage'
    | '/equipment-maintenance'
    | '/equipment-returns'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/mrp'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-entry-new'
    | '/production-reports'
    | '/purchase-reports'
    | '/purchase-requisition'
    | '/purchase-return'
    | '/quotation-entry'
    | '/receive-item'
    | '/reports'
    | '/request-for-quotation'
    | '/stock-adjustment'
    | '/transfer'
    | '/transfer-request'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/airline-consumables'
    | '/airline-equipments'
    | '/amenities'
    | '/approval-management'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/comparative-statement'
    | '/config-airline'
    | '/config-approval'
    | '/config-company'
    | '/config-item'
    | '/config-office'
    | '/config-price'
    | '/config-supplier'
    | '/config-warehouse'
    | '/consumable-allocation'
    | '/consumable-usage'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/equipment-damage'
    | '/equipment-maintenance'
    | '/equipment-returns'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/mrp'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-entry-new'
    | '/production-reports'
    | '/purchase-reports'
    | '/purchase-requisition'
    | '/purchase-return'
    | '/quotation-entry'
    | '/receive-item'
    | '/reports'
    | '/request-for-quotation'
    | '/stock-adjustment'
    | '/transfer'
    | '/transfer-request'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/airline-consumables'
    | '/airline-equipments'
    | '/amenities'
    | '/approval-management'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/comparative-statement'
    | '/config-airline'
    | '/config-approval'
    | '/config-company'
    | '/config-item'
    | '/config-office'
    | '/config-price'
    | '/config-supplier'
    | '/config-warehouse'
    | '/consumable-allocation'
    | '/consumable-usage'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/equipment-damage'
    | '/equipment-maintenance'
    | '/equipment-returns'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/mrp'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-entry-new'
    | '/production-reports'
    | '/purchase-reports'
    | '/purchase-requisition'
    | '/purchase-return'
    | '/quotation-entry'
    | '/receive-item'
    | '/reports'
    | '/request-for-quotation'
    | '/stock-adjustment'
    | '/transfer'
    | '/transfer-request'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AccountsApprovalsRoute: typeof AccountsApprovalsRoute
  AccountsExpensesRoute: typeof AccountsExpensesRoute
  AccountsInvoicesRoute: typeof AccountsInvoicesRoute
  AirlineConsumablesRoute: typeof AirlineConsumablesRoute
  AirlineEquipmentsRoute: typeof AirlineEquipmentsRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ApprovalManagementRoute: typeof ApprovalManagementRoute
  AuditRoute: typeof AuditRoute
  BakeryRoute: typeof BakeryRoute
  BomRoute: typeof BomRoute
  ComparativeStatementRoute: typeof ComparativeStatementRoute
  ConfigAirlineRoute: typeof ConfigAirlineRoute
  ConfigApprovalRoute: typeof ConfigApprovalRoute
  ConfigCompanyRoute: typeof ConfigCompanyRoute
  ConfigItemRoute: typeof ConfigItemRoute
  ConfigOfficeRoute: typeof ConfigOfficeRoute
  ConfigPriceRoute: typeof ConfigPriceRoute
  ConfigSupplierRoute: typeof ConfigSupplierRoute
  ConfigWarehouseRoute: typeof ConfigWarehouseRoute
  ConsumableAllocationRoute: typeof ConsumableAllocationRoute
  ConsumableUsageRoute: typeof ConsumableUsageRoute
  CookingTempRoute: typeof CookingTempRoute
  DemandOrdersRoute: typeof DemandOrdersRoute
  DispatchRoute: typeof DispatchRoute
  DispatchMonitoringRoute: typeof DispatchMonitoringRoute
  EquipmentDamageRoute: typeof EquipmentDamageRoute
  EquipmentMaintenanceRoute: typeof EquipmentMaintenanceRoute
  EquipmentReturnsRoute: typeof EquipmentReturnsRoute
  HygieneMonitoringRoute: typeof HygieneMonitoringRoute
  InventoryRoute: typeof InventoryRoute
  ItemIssueRoute: typeof ItemIssueRoute
  KitchenRoute: typeof KitchenRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MealPlanningRoute: typeof MealPlanningRoute
  MrpRoute: typeof MrpRoute
  OrderManagementRoute: typeof OrderManagementRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionEntryRoute: typeof ProductionEntryRoute
  ProductionEntryNewRoute: typeof ProductionEntryNewRoute
  ProductionReportsRoute: typeof ProductionReportsRoute
  PurchaseReportsRoute: typeof PurchaseReportsRoute
  PurchaseRequisitionRoute: typeof PurchaseRequisitionRoute
  PurchaseReturnRoute: typeof PurchaseReturnRoute
  QuotationEntryRoute: typeof QuotationEntryRoute
  ReceiveItemRoute: typeof ReceiveItemRoute
  ReportsRoute: typeof ReportsRoute
  RequestForQuotationRoute: typeof RequestForQuotationRoute
  StockAdjustmentRoute: typeof StockAdjustmentRoute
  TransferRoute: typeof TransferRoute
  TransferRequestRoute: typeof TransferRequestRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-request': {
      id: '/transfer-request'
      path: '/transfer-request'
      fullPath: '/transfer-request'
      preLoaderRoute: typeof TransferRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustment': {
      id: '/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof StockAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-for-quotation': {
      id: '/request-for-quotation'
      path: '/request-for-quotation'
      fullPath: '/request-for-quotation'
      preLoaderRoute: typeof RequestForQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive-item': {
      id: '/receive-item'
      path: '/receive-item'
      fullPath: '/receive-item'
      preLoaderRoute: typeof ReceiveItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotation-entry': {
      id: '/quotation-entry'
      path: '/quotation-entry'
      fullPath: '/quotation-entry'
      preLoaderRoute: typeof QuotationEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-return': {
      id: '/purchase-return'
      path: '/purchase-return'
      fullPath: '/purchase-return'
      preLoaderRoute: typeof PurchaseReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requisition': {
      id: '/purchase-requisition'
      path: '/purchase-requisition'
      fullPath: '/purchase-requisition'
      preLoaderRoute: typeof PurchaseRequisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-reports': {
      id: '/purchase-reports'
      path: '/purchase-reports'
      fullPath: '/purchase-reports'
      preLoaderRoute: typeof PurchaseReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-reports': {
      id: '/production-reports'
      path: '/production-reports'
      fullPath: '/production-reports'
      preLoaderRoute: typeof ProductionReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-entry-new': {
      id: '/production-entry-new'
      path: '/production-entry-new'
      fullPath: '/production-entry-new'
      preLoaderRoute: typeof ProductionEntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-entry': {
      id: '/production-entry'
      path: '/production-entry'
      fullPath: '/production-entry'
      preLoaderRoute: typeof ProductionEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-management': {
      id: '/order-management'
      path: '/order-management'
      fullPath: '/order-management'
      preLoaderRoute: typeof OrderManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrp': {
      id: '/mrp'
      path: '/mrp'
      fullPath: '/mrp'
      preLoaderRoute: typeof MrpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planning': {
      id: '/meal-planning'
      path: '/meal-planning'
      fullPath: '/meal-planning'
      preLoaderRoute: typeof MealPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-issue': {
      id: '/item-issue'
      path: '/item-issue'
      fullPath: '/item-issue'
      preLoaderRoute: typeof ItemIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hygiene-monitoring': {
      id: '/hygiene-monitoring'
      path: '/hygiene-monitoring'
      fullPath: '/hygiene-monitoring'
      preLoaderRoute: typeof HygieneMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-returns': {
      id: '/equipment-returns'
      path: '/equipment-returns'
      fullPath: '/equipment-returns'
      preLoaderRoute: typeof EquipmentReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-maintenance': {
      id: '/equipment-maintenance'
      path: '/equipment-maintenance'
      fullPath: '/equipment-maintenance'
      preLoaderRoute: typeof EquipmentMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-damage': {
      id: '/equipment-damage'
      path: '/equipment-damage'
      fullPath: '/equipment-damage'
      preLoaderRoute: typeof EquipmentDamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-monitoring': {
      id: '/dispatch-monitoring'
      path: '/dispatch-monitoring'
      fullPath: '/dispatch-monitoring'
      preLoaderRoute: typeof DispatchMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand-orders': {
      id: '/demand-orders'
      path: '/demand-orders'
      fullPath: '/demand-orders'
      preLoaderRoute: typeof DemandOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking-temp': {
      id: '/cooking-temp'
      path: '/cooking-temp'
      fullPath: '/cooking-temp'
      preLoaderRoute: typeof CookingTempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable-usage': {
      id: '/consumable-usage'
      path: '/consumable-usage'
      fullPath: '/consumable-usage'
      preLoaderRoute: typeof ConsumableUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable-allocation': {
      id: '/consumable-allocation'
      path: '/consumable-allocation'
      fullPath: '/consumable-allocation'
      preLoaderRoute: typeof ConsumableAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-warehouse': {
      id: '/config-warehouse'
      path: '/config-warehouse'
      fullPath: '/config-warehouse'
      preLoaderRoute: typeof ConfigWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-supplier': {
      id: '/config-supplier'
      path: '/config-supplier'
      fullPath: '/config-supplier'
      preLoaderRoute: typeof ConfigSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-price': {
      id: '/config-price'
      path: '/config-price'
      fullPath: '/config-price'
      preLoaderRoute: typeof ConfigPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-office': {
      id: '/config-office'
      path: '/config-office'
      fullPath: '/config-office'
      preLoaderRoute: typeof ConfigOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-item': {
      id: '/config-item'
      path: '/config-item'
      fullPath: '/config-item'
      preLoaderRoute: typeof ConfigItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-company': {
      id: '/config-company'
      path: '/config-company'
      fullPath: '/config-company'
      preLoaderRoute: typeof ConfigCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-approval': {
      id: '/config-approval'
      path: '/config-approval'
      fullPath: '/config-approval'
      preLoaderRoute: typeof ConfigApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-airline': {
      id: '/config-airline'
      path: '/config-airline'
      fullPath: '/config-airline'
      preLoaderRoute: typeof ConfigAirlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative-statement': {
      id: '/comparative-statement'
      path: '/comparative-statement'
      fullPath: '/comparative-statement'
      preLoaderRoute: typeof ComparativeStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery': {
      id: '/bakery'
      path: '/bakery'
      fullPath: '/bakery'
      preLoaderRoute: typeof BakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-management': {
      id: '/approval-management'
      path: '/approval-management'
      fullPath: '/approval-management'
      preLoaderRoute: typeof ApprovalManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airline-equipments': {
      id: '/airline-equipments'
      path: '/airline-equipments'
      fullPath: '/airline-equipments'
      preLoaderRoute: typeof AirlineEquipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airline-consumables': {
      id: '/airline-consumables'
      path: '/airline-consumables'
      fullPath: '/airline-consumables'
      preLoaderRoute: typeof AirlineConsumablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-invoices': {
      id: '/accounts-invoices'
      path: '/accounts-invoices'
      fullPath: '/accounts-invoices'
      preLoaderRoute: typeof AccountsInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-expenses': {
      id: '/accounts-expenses'
      path: '/accounts-expenses'
      fullPath: '/accounts-expenses'
      preLoaderRoute: typeof AccountsExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-approvals': {
      id: '/accounts-approvals'
      path: '/accounts-approvals'
      fullPath: '/accounts-approvals'
      preLoaderRoute: typeof AccountsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AccountsApprovalsRoute: AccountsApprovalsRoute,
  AccountsExpensesRoute: AccountsExpensesRoute,
  AccountsInvoicesRoute: AccountsInvoicesRoute,
  AirlineConsumablesRoute: AirlineConsumablesRoute,
  AirlineEquipmentsRoute: AirlineEquipmentsRoute,
  AmenitiesRoute: AmenitiesRoute,
  ApprovalManagementRoute: ApprovalManagementRoute,
  AuditRoute: AuditRoute,
  BakeryRoute: BakeryRoute,
  BomRoute: BomRoute,
  ComparativeStatementRoute: ComparativeStatementRoute,
  ConfigAirlineRoute: ConfigAirlineRoute,
  ConfigApprovalRoute: ConfigApprovalRoute,
  ConfigCompanyRoute: ConfigCompanyRoute,
  ConfigItemRoute: ConfigItemRoute,
  ConfigOfficeRoute: ConfigOfficeRoute,
  ConfigPriceRoute: ConfigPriceRoute,
  ConfigSupplierRoute: ConfigSupplierRoute,
  ConfigWarehouseRoute: ConfigWarehouseRoute,
  ConsumableAllocationRoute: ConsumableAllocationRoute,
  ConsumableUsageRoute: ConsumableUsageRoute,
  CookingTempRoute: CookingTempRoute,
  DemandOrdersRoute: DemandOrdersRoute,
  DispatchRoute: DispatchRoute,
  DispatchMonitoringRoute: DispatchMonitoringRoute,
  EquipmentDamageRoute: EquipmentDamageRoute,
  EquipmentMaintenanceRoute: EquipmentMaintenanceRoute,
  EquipmentReturnsRoute: EquipmentReturnsRoute,
  HygieneMonitoringRoute: HygieneMonitoringRoute,
  InventoryRoute: InventoryRoute,
  ItemIssueRoute: ItemIssueRoute,
  KitchenRoute: KitchenRoute,
  MaintenanceRoute: MaintenanceRoute,
  MealPlanningRoute: MealPlanningRoute,
  MrpRoute: MrpRoute,
  OrderManagementRoute: OrderManagementRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionEntryRoute: ProductionEntryRoute,
  ProductionEntryNewRoute: ProductionEntryNewRoute,
  ProductionReportsRoute: ProductionReportsRoute,
  PurchaseReportsRoute: PurchaseReportsRoute,
  PurchaseRequisitionRoute: PurchaseRequisitionRoute,
  PurchaseReturnRoute: PurchaseReturnRoute,
  QuotationEntryRoute: QuotationEntryRoute,
  ReceiveItemRoute: ReceiveItemRoute,
  ReportsRoute: ReportsRoute,
  RequestForQuotationRoute: RequestForQuotationRoute,
  StockAdjustmentRoute: StockAdjustmentRoute,
  TransferRoute: TransferRoute,
  TransferRequestRoute: TransferRequestRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
