/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StockAdjustmentRouteImport } from './routes/stock-adjustment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReceiveItemRouteImport } from './routes/receive-item'
import { Route as PurchaseRequisitionRouteImport } from './routes/purchase-requisition'
import { Route as ProductionReportsRouteImport } from './routes/production-reports'
import { Route as ProductionEntryRouteImport } from './routes/production-entry'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as OrderManagementRouteImport } from './routes/order-management'
import { Route as MealPlanningRouteImport } from './routes/meal-planning'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ItemIssueRouteImport } from './routes/item-issue'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HygieneMonitoringRouteImport } from './routes/hygiene-monitoring'
import { Route as DispatchMonitoringRouteImport } from './routes/dispatch-monitoring'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DemandOrdersRouteImport } from './routes/demand-orders'
import { Route as CookingTempRouteImport } from './routes/cooking-temp'
import { Route as BomRouteImport } from './routes/bom'
import { Route as BakeryRouteImport } from './routes/bakery'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AccountsInvoicesRouteImport } from './routes/accounts-invoices'
import { Route as AccountsExpensesRouteImport } from './routes/accounts-expenses'
import { Route as AccountsApprovalsRouteImport } from './routes/accounts-approvals'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentRoute = StockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveItemRoute = ReceiveItemRouteImport.update({
  id: '/receive-item',
  path: '/receive-item',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequisitionRoute = PurchaseRequisitionRouteImport.update({
  id: '/purchase-requisition',
  path: '/purchase-requisition',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionReportsRoute = ProductionReportsRouteImport.update({
  id: '/production-reports',
  path: '/production-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionEntryRoute = ProductionEntryRouteImport.update({
  id: '/production-entry',
  path: '/production-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderManagementRoute = OrderManagementRouteImport.update({
  id: '/order-management',
  path: '/order-management',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanningRoute = MealPlanningRouteImport.update({
  id: '/meal-planning',
  path: '/meal-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIssueRoute = ItemIssueRouteImport.update({
  id: '/item-issue',
  path: '/item-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HygieneMonitoringRoute = HygieneMonitoringRouteImport.update({
  id: '/hygiene-monitoring',
  path: '/hygiene-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchMonitoringRoute = DispatchMonitoringRouteImport.update({
  id: '/dispatch-monitoring',
  path: '/dispatch-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandOrdersRoute = DemandOrdersRouteImport.update({
  id: '/demand-orders',
  path: '/demand-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingTempRoute = CookingTempRouteImport.update({
  id: '/cooking-temp',
  path: '/cooking-temp',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryRoute = BakeryRouteImport.update({
  id: '/bakery',
  path: '/bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsInvoicesRoute = AccountsInvoicesRouteImport.update({
  id: '/accounts-invoices',
  path: '/accounts-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsExpensesRoute = AccountsExpensesRouteImport.update({
  id: '/accounts-expenses',
  path: '/accounts-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsApprovalsRoute = AccountsApprovalsRouteImport.update({
  id: '/accounts-approvals',
  path: '/accounts-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/amenities': typeof AmenitiesRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/amenities': typeof AmenitiesRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/accounts-approvals': typeof AccountsApprovalsRoute
  '/accounts-expenses': typeof AccountsExpensesRoute
  '/accounts-invoices': typeof AccountsInvoicesRoute
  '/amenities': typeof AmenitiesRoute
  '/audit': typeof AuditRoute
  '/bakery': typeof BakeryRoute
  '/bom': typeof BomRoute
  '/cooking-temp': typeof CookingTempRoute
  '/demand-orders': typeof DemandOrdersRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-monitoring': typeof DispatchMonitoringRoute
  '/hygiene-monitoring': typeof HygieneMonitoringRoute
  '/inventory': typeof InventoryRoute
  '/item-issue': typeof ItemIssueRoute
  '/kitchen': typeof KitchenRoute
  '/maintenance': typeof MaintenanceRoute
  '/meal-planning': typeof MealPlanningRoute
  '/order-management': typeof OrderManagementRoute
  '/procurement': typeof ProcurementRoute
  '/production-entry': typeof ProductionEntryRoute
  '/production-reports': typeof ProductionReportsRoute
  '/purchase-requisition': typeof PurchaseRequisitionRoute
  '/receive-item': typeof ReceiveItemRoute
  '/reports': typeof ReportsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/amenities'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-reports'
    | '/purchase-requisition'
    | '/receive-item'
    | '/reports'
    | '/stock-adjustment'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/amenities'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-reports'
    | '/purchase-requisition'
    | '/receive-item'
    | '/reports'
    | '/stock-adjustment'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/accounts-approvals'
    | '/accounts-expenses'
    | '/accounts-invoices'
    | '/amenities'
    | '/audit'
    | '/bakery'
    | '/bom'
    | '/cooking-temp'
    | '/demand-orders'
    | '/dispatch'
    | '/dispatch-monitoring'
    | '/hygiene-monitoring'
    | '/inventory'
    | '/item-issue'
    | '/kitchen'
    | '/maintenance'
    | '/meal-planning'
    | '/order-management'
    | '/procurement'
    | '/production-entry'
    | '/production-reports'
    | '/purchase-requisition'
    | '/receive-item'
    | '/reports'
    | '/stock-adjustment'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AccountsApprovalsRoute: typeof AccountsApprovalsRoute
  AccountsExpensesRoute: typeof AccountsExpensesRoute
  AccountsInvoicesRoute: typeof AccountsInvoicesRoute
  AmenitiesRoute: typeof AmenitiesRoute
  AuditRoute: typeof AuditRoute
  BakeryRoute: typeof BakeryRoute
  BomRoute: typeof BomRoute
  CookingTempRoute: typeof CookingTempRoute
  DemandOrdersRoute: typeof DemandOrdersRoute
  DispatchRoute: typeof DispatchRoute
  DispatchMonitoringRoute: typeof DispatchMonitoringRoute
  HygieneMonitoringRoute: typeof HygieneMonitoringRoute
  InventoryRoute: typeof InventoryRoute
  ItemIssueRoute: typeof ItemIssueRoute
  KitchenRoute: typeof KitchenRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MealPlanningRoute: typeof MealPlanningRoute
  OrderManagementRoute: typeof OrderManagementRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionEntryRoute: typeof ProductionEntryRoute
  ProductionReportsRoute: typeof ProductionReportsRoute
  PurchaseRequisitionRoute: typeof PurchaseRequisitionRoute
  ReceiveItemRoute: typeof ReceiveItemRoute
  ReportsRoute: typeof ReportsRoute
  StockAdjustmentRoute: typeof StockAdjustmentRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustment': {
      id: '/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof StockAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive-item': {
      id: '/receive-item'
      path: '/receive-item'
      fullPath: '/receive-item'
      preLoaderRoute: typeof ReceiveItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requisition': {
      id: '/purchase-requisition'
      path: '/purchase-requisition'
      fullPath: '/purchase-requisition'
      preLoaderRoute: typeof PurchaseRequisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-reports': {
      id: '/production-reports'
      path: '/production-reports'
      fullPath: '/production-reports'
      preLoaderRoute: typeof ProductionReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-entry': {
      id: '/production-entry'
      path: '/production-entry'
      fullPath: '/production-entry'
      preLoaderRoute: typeof ProductionEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-management': {
      id: '/order-management'
      path: '/order-management'
      fullPath: '/order-management'
      preLoaderRoute: typeof OrderManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planning': {
      id: '/meal-planning'
      path: '/meal-planning'
      fullPath: '/meal-planning'
      preLoaderRoute: typeof MealPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item-issue': {
      id: '/item-issue'
      path: '/item-issue'
      fullPath: '/item-issue'
      preLoaderRoute: typeof ItemIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hygiene-monitoring': {
      id: '/hygiene-monitoring'
      path: '/hygiene-monitoring'
      fullPath: '/hygiene-monitoring'
      preLoaderRoute: typeof HygieneMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-monitoring': {
      id: '/dispatch-monitoring'
      path: '/dispatch-monitoring'
      fullPath: '/dispatch-monitoring'
      preLoaderRoute: typeof DispatchMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand-orders': {
      id: '/demand-orders'
      path: '/demand-orders'
      fullPath: '/demand-orders'
      preLoaderRoute: typeof DemandOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking-temp': {
      id: '/cooking-temp'
      path: '/cooking-temp'
      fullPath: '/cooking-temp'
      preLoaderRoute: typeof CookingTempRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery': {
      id: '/bakery'
      path: '/bakery'
      fullPath: '/bakery'
      preLoaderRoute: typeof BakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-invoices': {
      id: '/accounts-invoices'
      path: '/accounts-invoices'
      fullPath: '/accounts-invoices'
      preLoaderRoute: typeof AccountsInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-expenses': {
      id: '/accounts-expenses'
      path: '/accounts-expenses'
      fullPath: '/accounts-expenses'
      preLoaderRoute: typeof AccountsExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-approvals': {
      id: '/accounts-approvals'
      path: '/accounts-approvals'
      fullPath: '/accounts-approvals'
      preLoaderRoute: typeof AccountsApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AccountsApprovalsRoute: AccountsApprovalsRoute,
  AccountsExpensesRoute: AccountsExpensesRoute,
  AccountsInvoicesRoute: AccountsInvoicesRoute,
  AmenitiesRoute: AmenitiesRoute,
  AuditRoute: AuditRoute,
  BakeryRoute: BakeryRoute,
  BomRoute: BomRoute,
  CookingTempRoute: CookingTempRoute,
  DemandOrdersRoute: DemandOrdersRoute,
  DispatchRoute: DispatchRoute,
  DispatchMonitoringRoute: DispatchMonitoringRoute,
  HygieneMonitoringRoute: HygieneMonitoringRoute,
  InventoryRoute: InventoryRoute,
  ItemIssueRoute: ItemIssueRoute,
  KitchenRoute: KitchenRoute,
  MaintenanceRoute: MaintenanceRoute,
  MealPlanningRoute: MealPlanningRoute,
  OrderManagementRoute: OrderManagementRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionEntryRoute: ProductionEntryRoute,
  ProductionReportsRoute: ProductionReportsRoute,
  PurchaseRequisitionRoute: PurchaseRequisitionRoute,
  ReceiveItemRoute: ReceiveItemRoute,
  ReportsRoute: ReportsRoute,
  StockAdjustmentRoute: StockAdjustmentRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
